### ISSUE TITLE
invalid index to scalar variable.

### ISSUE THREAD

**Issue by luanle-padua** [zzilch/RPLAN-Toolbox#2]
Hello,

I am trying to run the test.py, but it comes out with this error:

  File ~\Downloads\RPLAN-Toolbox-master\RPLAN-Toolbox-master\rplan\floorplan.py:204 in _get_rooms
    c = stats.mode(self.category[region.coords[:,0],region.coords[:,1]])[0][0]

IndexError: invalid index to scalar variable.

Could you please help me with this?

Thank you
Luan
![image](https://github.com/zzilch/RPLAN-Toolbox/assets/113601110/64533fcf-7b6e-4888-869c-1e9d8b005fc2)

**Comment by onefish51** [comment]
I encountered the same problem while running it.
```bash
PS E:\py_code\RPLAN-Toolbox> python .\test.py
Traceback (most recent call last):
  File "E:\py_code\RPLAN-Toolbox\test.py", line 12, in <module>
    fp = Floorplan(file_path)
  File "E:\py_code\RPLAN-Toolbox\rplan\floorplan.py", line 41, in __init__
    self._get_rooms()
  File "E:\py_code\RPLAN-Toolbox\rplan\floorplan.py", line 207, in _get_rooms
    c = stats.mode(self.category[region.coords[:,0],region.coords[:,1]])[0][0]
IndexError: invalid index to scalar variable.
```
